In [1]:
import argparse
import os
import pathlib
import sys
from functools import reduce

import duckdb
import pandas as pd
from image_analysis_3D.file_utils.arg_parsing_utils import parse_args
from image_analysis_3D.file_utils.notebook_init_utils import (
    bandicoot_check,
    init_notebook,
)

root_dir, in_notebook = init_notebook()

profile_base_dir = bandicoot_check(
    pathlib.Path(os.path.expanduser("~/mnt/bandicoot/NF1_organoid_data")).resolve(),
    root_dir,
)
profile_base_dir = root_dir

In [2]:
if not in_notebook:
    args = parse_args()
    well_fov = args["well_fov"]
    patient = args["patient"]
    output_features_subparent_name = args["output_features_subparent_name"]
    image_based_profiles_subparent_name = args["image_based_profiles_subparent_name"]


else:
    well_fov = "E9-1"
    patient = "NF0014_T1"
    output_features_subparent_name = "extracted_features"
    image_based_profiles_subparent_name = "image_based_profiles"


result_path = pathlib.Path(
    f"{profile_base_dir}/data/{patient}/{output_features_subparent_name}/{well_fov}"
).resolve(strict=True)
database_path = pathlib.Path(
    f"{profile_base_dir}/data/{patient}/{image_based_profiles_subparent_name}/0.converted_profiles/{well_fov}"
).resolve()
database_path.mkdir(parents=True, exist_ok=True)
# create the sqlite database
sqlite_path = database_path / f"{well_fov}.duckdb"
DB_structure_path = pathlib.Path(
    f"{root_dir}/4.processing_image_based_profiles/data/DB_structures/DB_structure_db.duckdb"
).resolve(strict=True)

# get a list of all parquets in the directory recursively
parquet_files = list(result_path.rglob("*.parquet"))
parquet_files.sort()
print(len(parquet_files), "parquet files found")
if len(parquet_files) != 101:
    raise ValueError(f"Expected 101 parquet files, but found {len(parquet_files)}")

101 parquet files found

In [3]:
# create the nested dictionary to hold the feature types and compartments
feature_types = [
    "AreaSizeShape",
    "Colocalization",
    "Intensity",
    "Granularity",
    "Neighbors",
    "SAMMed3D",
    "Texture",
    "CHAMMI75",
]
compartments = ["Organoid", "Nuclei", "Cell", "Cytoplasm", "Nucleocentric"]

In [4]:
output_dict = {
    compartment: {
        feature_type: []
        for feature_type in feature_types
        if not (
            compartment == "Nucleocentric"
            and feature_type.lower() not in ["chammi75", "sammed3d"]
        )
    }
    for compartment in compartments
}
output_dict

{'Organoid': {'AreaSizeShape': [],
  'Colocalization': [],
  'Intensity': [],
  'Granularity': [],
  'Neighbors': [],
  'SAMMed3D': [],
  'Texture': [],
  'CHAMMI75': []},
 'Nuclei': {'AreaSizeShape': [],
  'Colocalization': [],
  'Intensity': [],
  'Granularity': [],
  'Neighbors': [],
  'SAMMed3D': [],
  'Texture': [],
  'CHAMMI75': []},
 'Cell': {'AreaSizeShape': [],
  'Colocalization': [],
  'Intensity': [],
  'Granularity': [],
  'Neighbors': [],
  'SAMMed3D': [],
  'Texture': [],
  'CHAMMI75': []},
 'Cytoplasm': {'AreaSizeShape': [],
  'Colocalization': [],
  'Intensity': [],
  'Granularity': [],
  'Neighbors': [],
  'SAMMed3D': [],
  'Texture': [],
  'CHAMMI75': []},
 'Nucleocentric': {'SAMMed3D': [], 'CHAMMI75': []}}

In [5]:
files = list(result_path.rglob("*.parquet"))
files_df = pd.DataFrame({"file_path": files})
files_df["file_name"] = files_df["file_path"].apply(lambda x: x.name)
files_df["compartment"] = files_df["file_name"].apply(lambda x: x.split("_")[0])
files_df["channel"] = files_df["file_name"].apply(lambda x: x.split("_")[1])
files_df["feature_type"] = files_df["file_name"].apply(
    lambda x: x.split("_")[2].split(".parquet")[0]
)
file_path = files_df.pop("file_path")
files_df.insert(4, "file_path", file_path)
files_df.head()

,file_name,compartment,channel,feature_type,file_path
0,Nuclei_ER_SAMMed3D_GPU_features.parquet,Nuclei,ER,SAMMed3D,/home/lippincm/Documents/NF1_3D_organoid_profi...
1,Cell_AGP_Granularity_CPU_features.parquet,Cell,AGP,Granularity,/home/lippincm/Documents/NF1_3D_organoid_profi...
2,Cytoplasm_Mito_Intensity_CPU_features.parquet,Cytoplasm,Mito,Intensity,/home/lippincm/Documents/NF1_3D_organoid_profi...
3,Nuclei_AGP_Intensity_CPU_features.parquet,Nuclei,AGP,Intensity,/home/lippincm/Documents/NF1_3D_organoid_profi...
4,Organoid_AGP_Granularity_CPU_features.parquet,Organoid,AGP,Granularity,/home/lippincm/Documents/NF1_3D_organoid_profi...

In [6]:
for i, row in files_df.iterrows():
    compartment = row["compartment"]
    feature_type = row["feature_type"]
    channel = row["channel"]
    file_path = row["file_path"]
    output_dict[compartment][feature_type].append(file_path)
output_dict

{'Organoid': {'AreaSizeShape': [PosixPath('/home/lippincm/Documents/NF1_3D_organoid_profiling_pipeline/data/NF0014_T1/extracted_features/E9-1/Organoid_NoChannel_AreaSizeShape_CPU_features.parquet')],
  'Colocalization': [PosixPath('/home/lippincm/Documents/NF1_3D_organoid_profiling_pipeline/data/NF0014_T1/extracted_features/E9-1/Organoid_DNA-ER_Colocalization_CPU_features.parquet'),
   PosixPath('/home/lippincm/Documents/NF1_3D_organoid_profiling_pipeline/data/NF0014_T1/extracted_features/E9-1/Organoid_DNA-Mito_Colocalization_CPU_features.parquet'),
   PosixPath('/home/lippincm/Documents/NF1_3D_organoid_profiling_pipeline/data/NF0014_T1/extracted_features/E9-1/Organoid_ER-Mito_Colocalization_CPU_features.parquet'),
   PosixPath('/home/lippincm/Documents/NF1_3D_organoid_profiling_pipeline/data/NF0014_T1/extracted_features/E9-1/Organoid_Mito-AGP_Colocalization_CPU_features.parquet'),
   PosixPath('/home/lippincm/Documents/NF1_3D_organoid_profiling_pipeline/data/NF0014_T1/extracted_features/E9-1/Organoid_ER-AGP_Colocalization_CPU_features.parquet'),
   PosixPath('/home/lippincm/Documents/NF1_3D_organoid_profiling_pipeline/data/NF0014_T1/extracted_features/E9-1/Organoid_DNA-AGP_Colocalization_CPU_features.parquet')],
  'Intensity': [PosixPath('/home/lippincm/Documents/NF1_3D_organoid_profiling_pipeline/data/NF0014_T1/extracted_features/E9-1/Organoid_Mito_Intensity_CPU_features.parquet'),
   PosixPath('/home/lippincm/Documents/NF1_3D_organoid_profiling_pipeline/data/NF0014_T1/extracted_features/E9-1/Organoid_AGP_Intensity_CPU_features.parquet'),
   PosixPath('/home/lippincm/Documents/NF1_3D_organoid_profiling_pipeline/data/NF0014_T1/extracted_features/E9-1/Organoid_ER_Intensity_CPU_features.parquet'),
   PosixPath('/home/lippincm/Documents/NF1_3D_organoid_profiling_pipeline/data/NF0014_T1/extracted_features/E9-1/Organoid_DNA_Intensity_CPU_features.parquet')],
  'Granularity': [PosixPath('/home/lippincm/Documents/NF1_3D_organoid_profiling_pipeline/data/NF0014_T1/extracted_features/E9-1/Organoid_AGP_Granularity_CPU_features.parquet'),
   PosixPath('/home/lippincm/Documents/NF1_3D_organoid_profiling_pipeline/data/NF0014_T1/extracted_features/E9-1/Organoid_Mito_Granularity_CPU_features.parquet'),
   PosixPath('/home/lippincm/Documents/NF1_3D_organoid_profiling_pipeline/data/NF0014_T1/extracted_features/E9-1/Organoid_DNA_Granularity_CPU_features.parquet'),
   PosixPath('/home/lippincm/Documents/NF1_3D_organoid_profiling_pipeline/data/NF0014_T1/extracted_features/E9-1/Organoid_ER_Granularity_CPU_features.parquet')],
  'Neighbors': [],
  'SAMMed3D': [PosixPath('/home/lippincm/Documents/NF1_3D_organoid_profiling_pipeline/data/NF0014_T1/extracted_features/E9-1/Organoid_DNA_SAMMed3D_GPU_features.parquet'),
   PosixPath('/home/lippincm/Documents/NF1_3D_organoid_profiling_pipeline/data/NF0014_T1/extracted_features/E9-1/Organoid_AGP_SAMMed3D_GPU_features.parquet'),
   PosixPath('/home/lippincm/Documents/NF1_3D_organoid_profiling_pipeline/data/NF0014_T1/extracted_features/E9-1/Organoid_Mito_SAMMed3D_GPU_features.parquet'),
   PosixPath('/home/lippincm/Documents/NF1_3D_organoid_profiling_pipeline/data/NF0014_T1/extracted_features/E9-1/Organoid_ER_SAMMed3D_GPU_features.parquet')],
  'Texture': [PosixPath('/home/lippincm/Documents/NF1_3D_organoid_profiling_pipeline/data/NF0014_T1/extracted_features/E9-1/Organoid_DNA_Texture_CPU_features.parquet'),
   PosixPath('/home/lippincm/Documents/NF1_3D_organoid_profiling_pipeline/data/NF0014_T1/extracted_features/E9-1/Organoid_ER_Texture_CPU_features.parquet'),
   PosixPath('/home/lippincm/Documents/NF1_3D_organoid_profiling_pipeline/data/NF0014_T1/extracted_features/E9-1/Organoid_AGP_Texture_CPU_features.parquet'),
   PosixPath('/home/lippincm/Documents/NF1_3D_organoid_profiling_pipeline/data/NF0014_T1/extracted_features/E9-1/Organoid_Mito_Texture_CPU_features.parquet')],
  'CHAMMI75': []},
 'Nuclei': {'AreaSizeShape': [PosixPath('/home/lippincm/Documents/NF1_3D_organoid_profiling_pipeline/data/NF0014_T1/extracted_features/E9-1/Nuclei_NoChannel_AreaSizeShape_CPU_features.parquet')],
  'Colocalization': [PosixPath('/home/lippincm/Documents/NF1_3D_organoid_profiling_pipeline/data/NF0014_T1/extracted_features/E9-1/Nuclei_ER-AGP_Colocalization_CPU_features.parquet'),
   PosixPath('/home/lippincm/Documents/NF1_3D_organoid_profiling_pipeline/data/NF0014_T1/extracted_features/E9-1/Nuclei_ER-Mito_Colocalization_CPU_features.parquet'),
   PosixPath('/home/lippincm/Documents/NF1_3D_organoid_profiling_pipeline/data/NF0014_T1/extracted_features/E9-1/Nuclei_DNA-Mito_Colocalization_CPU_features.parquet'),
   PosixPath('/home/lippincm/Documents/NF1_3D_organoid_profiling_pipeline/data/NF0014_T1/extracted_features/E9-1/Nuclei_DNA-AGP_Colocalization_CPU_features.parquet'),
   PosixPath('/home/lippincm/Documents/NF1_3D_organoid_profiling_pipeline/data/NF0014_T1/extracted_features/E9-1/Nuclei_Mito-AGP_Colocalization_CPU_features.parquet'),
   PosixPath('/home/lippincm/Documents/NF1_3D_organoid_profiling_pipeline/data/NF0014_T1/extracted_features/E9-1/Nuclei_DNA-ER_Colocalization_CPU_features.parquet')],
  'Intensity': [PosixPath('/home/lippincm/Documents/NF1_3D_organoid_profiling_pipeline/data/NF0014_T1/extracted_features/E9-1/Nuclei_AGP_Intensity_CPU_features.parquet'),
   PosixPath('/home/lippincm/Documents/NF1_3D_organoid_profiling_pipeline/data/NF0014_T1/extracted_features/E9-1/Nuclei_Mito_Intensity_CPU_features.parquet'),
   PosixPath('/home/lippincm/Documents/NF1_3D_organoid_profiling_pipeline/data/NF0014_T1/extracted_features/E9-1/Nuclei_DNA_Intensity_CPU_features.parquet'),
   PosixPath('/home/lippincm/Documents/NF1_3D_organoid_profiling_pipeline/data/NF0014_T1/extracted_features/E9-1/Nuclei_ER_Intensity_CPU_features.parquet')],
  'Granularity': [PosixPath('/home/lippincm/Documents/NF1_3D_organoid_profiling_pipeline/data/NF0014_T1/extracted_features/E9-1/Nuclei_Mito_Granularity_CPU_features.parquet'),
   PosixPath('/home/lippincm/Documents/NF1_3D_organoid_profiling_pipeline/data/NF0014_T1/extracted_features/E9-1/Nuclei_ER_Granularity_CPU_features.parquet'),
   PosixPath('/home/lippincm/Documents/NF1_3D_organoid_profiling_pipeline/data/NF0014_T1/extracted_features/E9-1/Nuclei_AGP_Granularity_CPU_features.parquet'),
   PosixPath('/home/lippincm/Documents/NF1_3D_organoid_profiling_pipeline/data/NF0014_T1/extracted_features/E9-1/Nuclei_DNA_Granularity_CPU_features.parquet')],
  'Neighbors': [PosixPath('/home/lippincm/Documents/NF1_3D_organoid_profiling_pipeline/data/NF0014_T1/extracted_features/E9-1/Nuclei_NoChannel_Neighbors_CPU_features.parquet')],
  'SAMMed3D': [PosixPath('/home/lippincm/Documents/NF1_3D_organoid_profiling_pipeline/data/NF0014_T1/extracted_features/E9-1/Nuclei_ER_SAMMed3D_GPU_features.parquet'),
   PosixPath('/home/lippincm/Documents/NF1_3D_organoid_profiling_pipeline/data/NF0014_T1/extracted_features/E9-1/Nuclei_DNA_SAMMed3D_GPU_features.parquet'),
   PosixPath('/home/lippincm/Documents/NF1_3D_organoid_profiling_pipeline/data/NF0014_T1/extracted_features/E9-1/Nuclei_AGP_SAMMed3D_GPU_features.parquet'),
   PosixPath('/home/lippincm/Documents/NF1_3D_organoid_profiling_pipeline/data/NF0014_T1/extracted_features/E9-1/Nuclei_Mito_SAMMed3D_GPU_features.parquet')],
  'Texture': [PosixPath('/home/lippincm/Documents/NF1_3D_organoid_profiling_pipeline/data/NF0014_T1/extracted_features/E9-1/Nuclei_DNA_Texture_CPU_features.parquet'),
   PosixPath('/home/lippincm/Documents/NF1_3D_organoid_profiling_pipeline/data/NF0014_T1/extracted_features/E9-1/Nuclei_ER_Texture_CPU_features.parquet'),
   PosixPath('/home/lippincm/Documents/NF1_3D_organoid_profiling_pipeline/data/NF0014_T1/extracted_features/E9-1/Nuclei_AGP_Texture_CPU_features.parquet'),
   PosixPath('/home/lippincm/Documents/NF1_3D_organoid_profiling_pipeline/data/NF0014_T1/extracted_features/E9-1/Nuclei_Mito_Texture_CPU_features.parquet')],
  'CHAMMI75': []},
 'Cell': {'AreaSizeShape': [PosixPath('/home/lippincm/Documents/NF1_3D_organoid_profiling_pipeline/data/NF0014_T1/extracted_features/E9-1/Cell_NoChannel_AreaSizeShape_CPU_features.parquet')],
  'Colocalization': [PosixPath('/home/lippincm/Documents/NF1_3D_organoid_profiling_pipeline/data/NF0014_T1/extracted_features/E9-1/Cell_Mito-AGP_Colocalization_CPU_features.parquet'),
   PosixPath('/home/lippincm/Documents/NF1_3D_organoid_profiling_pipeline/data/NF0014_T1/extracted_features/E9-1/Cell_ER-Mito_Colocalization_CPU_features.parquet'),
   PosixPath('/home/lippincm/Documents/NF1_3D_organoid_profiling_pipeline/data/NF0014_T1/extracted_features/E9-1/Cell_DNA-ER_Colocalization_CPU_features.parquet'),
   PosixPath('/home/lippincm/Documents/NF1_3D_organoid_profiling_pipeline/data/NF0014_T1/extracted_features/E9-1/Cell_DNA-Mito_Colocalization_CPU_features.parquet'),
   PosixPath('/home/lippincm/Documents/NF1_3D_organoid_profiling_pipeline/data/NF0014_T1/extracted_features/E9-1/Cell_ER-AGP_Colocalization_CPU_features.parquet'),
   PosixPath('/home/lippincm/Documents/NF1_3D_organoid_profiling_pipeline/data/NF0014_T1/extracted_features/E9-1/Cell_DNA-AGP_Colocalization_CPU_features.parquet')],
  'Intensity': [PosixPath('/home/lippincm/Documents/NF1_3D_organoid_profiling_pipeline/data/NF0014_T1/extracted_features/E9-1/Cell_ER_Intensity_CPU_features.parquet'),
   PosixPath('/home/lippincm/Documents/NF1_3D_organoid_profiling_pipeline/data/NF0014_T1/extracted_features/E9-1/Cell_AGP_Intensity_CPU_features.parquet'),
   PosixPath('/home/lippincm/Documents/NF1_3D_organoid_profiling_pipeline/data/NF0014_T1/extracted_features/E9-1/Cell_DNA_Intensity_CPU_features.parquet'),
   PosixPath('/home/lippincm/Documents/NF1_3D_organoid_profiling_pipeline/data/NF0014_T1/extracted_features/E9-1/Cell_Mito_Intensity_CPU_features.parquet')],
  'Granularity': [PosixPath('/home/lippincm/Documents/NF1_3D_organoid_profiling_pipeline/data/NF0014_T1/extracted_features/E9-1/Cell_AGP_Granularity_CPU_features.parquet'),
   PosixPath('/home/lippincm/Documents/NF1_3D_organoid_profiling_pipeline/data/NF0014_T1/extracted_features/E9-1/Cell_ER_Granularity_CPU_features.parquet'),
   PosixPath('/home/lippincm/Documents/NF1_3D_organoid_profiling_pipeline/data/NF0014_T1/extracted_features/E9-1/Cell_Mito_Granularity_CPU_features.parquet'),
   PosixPath('/home/lippincm/Documents/NF1_3D_organoid_profiling_pipeline/data/NF0014_T1/extracted_features/E9-1/Cell_DNA_Granularity_CPU_features.parquet')],
  'Neighbors': [],
  'SAMMed3D': [PosixPath('/home/lippincm/Documents/NF1_3D_organoid_profiling_pipeline/data/NF0014_T1/extracted_features/E9-1/Cell_AGP_SAMMed3D_GPU_features.parquet'),
   PosixPath('/home/lippincm/Documents/NF1_3D_organoid_profiling_pipeline/data/NF0014_T1/extracted_features/E9-1/Cell_Mito_SAMMed3D_GPU_features.parquet'),
   PosixPath('/home/lippincm/Documents/NF1_3D_organoid_profiling_pipeline/data/NF0014_T1/extracted_features/E9-1/Cell_ER_SAMMed3D_GPU_features.parquet'),
   PosixPath('/home/lippincm/Documents/NF1_3D_organoid_profiling_pipeline/data/NF0014_T1/extracted_features/E9-1/Cell_DNA_SAMMed3D_GPU_features.parquet')],
  'Texture': [PosixPath('/home/lippincm/Documents/NF1_3D_organoid_profiling_pipeline/data/NF0014_T1/extracted_features/E9-1/Cell_DNA_Texture_CPU_features.parquet'),
   PosixPath('/home/lippincm/Documents/NF1_3D_organoid_profiling_pipeline/data/NF0014_T1/extracted_features/E9-1/Cell_Mito_Texture_CPU_features.parquet'),
   PosixPath('/home/lippincm/Documents/NF1_3D_organoid_profiling_pipeline/data/NF0014_T1/extracted_features/E9-1/Cell_AGP_Texture_CPU_features.parquet'),
   PosixPath('/home/lippincm/Documents/NF1_3D_organoid_profiling_pipeline/data/NF0014_T1/extracted_features/E9-1/Cell_ER_Texture_CPU_features.parquet')],
  'CHAMMI75': []},
 'Cytoplasm': {'AreaSizeShape': [PosixPath('/home/lippincm/Documents/NF1_3D_organoid_profiling_pipeline/data/NF0014_T1/extracted_features/E9-1/Cytoplasm_NoChannel_AreaSizeShape_CPU_features.parquet')],
  'Colocalization': [PosixPath('/home/lippincm/Documents/NF1_3D_organoid_profiling_pipeline/data/NF0014_T1/extracted_features/E9-1/Cytoplasm_ER-AGP_Colocalization_CPU_features.parquet'),
   PosixPath('/home/lippincm/Documents/NF1_3D_organoid_profiling_pipeline/data/NF0014_T1/extracted_features/E9-1/Cytoplasm_DNA-ER_Colocalization_CPU_features.parquet'),
   PosixPath('/home/lippincm/Documents/NF1_3D_organoid_profiling_pipeline/data/NF0014_T1/extracted_features/E9-1/Cytoplasm_ER-Mito_Colocalization_CPU_features.parquet'),
   PosixPath('/home/lippincm/Documents/NF1_3D_organoid_profiling_pipeline/data/NF0014_T1/extracted_features/E9-1/Cytoplasm_DNA-AGP_Colocalization_CPU_features.parquet'),
   PosixPath('/home/lippincm/Documents/NF1_3D_organoid_profiling_pipeline/data/NF0014_T1/extracted_features/E9-1/Cytoplasm_DNA-Mito_Colocalization_CPU_features.parquet'),
   PosixPath('/home/lippincm/Documents/NF1_3D_organoid_profiling_pipeline/data/NF0014_T1/extracted_features/E9-1/Cytoplasm_Mito-AGP_Colocalization_CPU_features.parquet')],
  'Intensity': [PosixPath('/home/lippincm/Documents/NF1_3D_organoid_profiling_pipeline/data/NF0014_T1/extracted_features/E9-1/Cytoplasm_Mito_Intensity_CPU_features.parquet'),
   PosixPath('/home/lippincm/Documents/NF1_3D_organoid_profiling_pipeline/data/NF0014_T1/extracted_features/E9-1/Cytoplasm_ER_Intensity_CPU_features.parquet'),
   PosixPath('/home/lippincm/Documents/NF1_3D_organoid_profiling_pipeline/data/NF0014_T1/extracted_features/E9-1/Cytoplasm_DNA_Intensity_CPU_features.parquet'),
   PosixPath('/home/lippincm/Documents/NF1_3D_organoid_profiling_pipeline/data/NF0014_T1/extracted_features/E9-1/Cytoplasm_AGP_Intensity_CPU_features.parquet')],
  'Granularity': [PosixPath('/home/lippincm/Documents/NF1_3D_organoid_profiling_pipeline/data/NF0014_T1/extracted_features/E9-1/Cytoplasm_ER_Granularity_CPU_features.parquet'),
   PosixPath('/home/lippincm/Documents/NF1_3D_organoid_profiling_pipeline/data/NF0014_T1/extracted_features/E9-1/Cytoplasm_Mito_Granularity_CPU_features.parquet'),
   PosixPath('/home/lippincm/Documents/NF1_3D_organoid_profiling_pipeline/data/NF0014_T1/extracted_features/E9-1/Cytoplasm_AGP_Granularity_CPU_features.parquet'),
   PosixPath('/home/lippincm/Documents/NF1_3D_organoid_profiling_pipeline/data/NF0014_T1/extracted_features/E9-1/Cytoplasm_DNA_Granularity_CPU_features.parquet')],
  'Neighbors': [],
  'SAMMed3D': [PosixPath('/home/lippincm/Documents/NF1_3D_organoid_profiling_pipeline/data/NF0014_T1/extracted_features/E9-1/Cytoplasm_ER_SAMMed3D_GPU_features.parquet'),
   PosixPath('/home/lippincm/Documents/NF1_3D_organoid_profiling_pipeline/data/NF0014_T1/extracted_features/E9-1/Cytoplasm_DNA_SAMMed3D_GPU_features.parquet'),
   PosixPath('/home/lippincm/Documents/NF1_3D_organoid_profiling_pipeline/data/NF0014_T1/extracted_features/E9-1/Cytoplasm_AGP_SAMMed3D_GPU_features.parquet'),
   PosixPath('/home/lippincm/Documents/NF1_3D_organoid_profiling_pipeline/data/NF0014_T1/extracted_features/E9-1/Cytoplasm_Mito_SAMMed3D_GPU_features.parquet')],
  'Texture': [PosixPath('/home/lippincm/Documents/NF1_3D_organoid_profiling_pipeline/data/NF0014_T1/extracted_features/E9-1/Cytoplasm_Mito_Texture_CPU_features.parquet'),
   PosixPath('/home/lippincm/Documents/NF1_3D_organoid_profiling_pipeline/data/NF0014_T1/extracted_features/E9-1/Cytoplasm_ER_Texture_CPU_features.parquet'),
   PosixPath('/home/lippincm/Documents/NF1_3D_organoid_profiling_pipeline/data/NF0014_T1/extracted_features/E9-1/Cytoplasm_AGP_Texture_CPU_features.parquet'),
   PosixPath('/home/lippincm/Documents/NF1_3D_organoid_profiling_pipeline/data/NF0014_T1/extracted_features/E9-1/Cytoplasm_DNA_Texture_CPU_features.parquet')],
  'CHAMMI75': []},
 'Nucleocentric': {'SAMMed3D': [PosixPath('/home/lippincm/Documents/NF1_3D_organoid_profiling_pipeline/data/NF0014_T1/extracted_features/E9-1/Nucleocentric_Mito_SAMMed3D_GPU_features.parquet'),
   PosixPath('/home/lippincm/Documents/NF1_3D_organoid_profiling_pipeline/data/NF0014_T1/extracted_features/E9-1/Nucleocentric_ER_SAMMed3D_GPU_features.parquet'),
   PosixPath('/home/lippincm/Documents/NF1_3D_organoid_profiling_pipeline/data/NF0014_T1/extracted_features/E9-1/Nucleocentric_AGP_SAMMed3D_GPU_features.parquet'),
   PosixPath('/home/lippincm/Documents/NF1_3D_organoid_profiling_pipeline/data/NF0014_T1/extracted_features/E9-1/Nucleocentric_DNA_SAMMed3D_GPU_features.parquet')],
  'CHAMMI75': [PosixPath('/home/lippincm/Documents/NF1_3D_organoid_profiling_pipeline/data/NF0014_T1/extracted_features/E9-1/Nucleocentric_DNA_CHAMMI75_GPU_features.parquet'),
   PosixPath('/home/lippincm/Documents/NF1_3D_organoid_profiling_pipeline/data/NF0014_T1/extracted_features/E9-1/Nucleocentric_Mito_CHAMMI75_GPU_features.parquet'),
   PosixPath('/home/lippincm/Documents/NF1_3D_organoid_profiling_pipeline/data/NF0014_T1/extracted_features/E9-1/Nucleocentric_AGP_CHAMMI75_GPU_features.parquet'),
   PosixPath('/home/lippincm/Documents/NF1_3D_organoid_profiling_pipeline/data/NF0014_T1/extracted_features/E9-1/Nucleocentric_ER_CHAMMI75_GPU_features.parquet')]}}

In [47]:
output_dict["Nucleocentric"]

{'SAMMed3D': [PosixPath('/home/lippincm/Documents/NF1_3D_organoid_profiling_pipeline/data/NF0014_T1/extracted_features/E9-1/Nucleocentric_Mito_SAMMed3D_GPU_features.parquet'),
  PosixPath('/home/lippincm/Documents/NF1_3D_organoid_profiling_pipeline/data/NF0014_T1/extracted_features/E9-1/Nucleocentric_ER_SAMMed3D_GPU_features.parquet'),
  PosixPath('/home/lippincm/Documents/NF1_3D_organoid_profiling_pipeline/data/NF0014_T1/extracted_features/E9-1/Nucleocentric_AGP_SAMMed3D_GPU_features.parquet'),
  PosixPath('/home/lippincm/Documents/NF1_3D_organoid_profiling_pipeline/data/NF0014_T1/extracted_features/E9-1/Nucleocentric_DNA_SAMMed3D_GPU_features.parquet')],
 'CHAMMI75': [PosixPath('/home/lippincm/Documents/NF1_3D_organoid_profiling_pipeline/data/NF0014_T1/extracted_features/E9-1/Nucleocentric_DNA_CHAMMI75_GPU_features.parquet'),
  PosixPath('/home/lippincm/Documents/NF1_3D_organoid_profiling_pipeline/data/NF0014_T1/extracted_features/E9-1/Nucleocentric_Mito_CHAMMI75_GPU_features.parquet'),
  PosixPath('/home/lippincm/Documents/NF1_3D_organoid_profiling_pipeline/data/NF0014_T1/extracted_features/E9-1/Nucleocentric_AGP_CHAMMI75_GPU_features.parquet'),
  PosixPath('/home/lippincm/Documents/NF1_3D_organoid_profiling_pipeline/data/NF0014_T1/extracted_features/E9-1/Nucleocentric_ER_CHAMMI75_GPU_features.parquet')]}

In [ ]:
final_df_dict = {compartment: {} for compartment in output_dict.keys()}
for compartment in output_dict.keys():
    for feature_type in output_dict[compartment].keys():
        if not output_dict[compartment][feature_type]:
            continue
        final_df_dict[compartment][feature_type] = reduce(
            lambda left, right: pd.merge(
                left,
                right,
                on=["object_id", "image_set"],
                how="left",
            ),
            [pd.read_parquet(file) for file in output_dict[compartment][feature_type]],
        )
# ensure the object_id column is int before merging
for compartment in final_df_dict.keys():
    for feature_type in final_df_dict[compartment].keys():
        final_df_dict[compartment][feature_type]["object_id"] = final_df_dict[
            compartment
        ][feature_type]["object_id"].astype(int)

In [51]:
final_df_dict["Nucleocentric"]["SAMMed3D"]

,object_id,image_set,Nucleocentric_Mito_CHAMMI75_Feature0,Nucleocentric_Mito_CHAMMI75_Feature1,Nucleocentric_Mito_CHAMMI75_Feature10,Nucleocentric_Mito_CHAMMI75_Feature100,Nucleocentric_Mito_CHAMMI75_Feature101,Nucleocentric_Mito_CHAMMI75_Feature102,Nucleocentric_Mito_CHAMMI75_Feature103,Nucleocentric_Mito_CHAMMI75_Feature104,...,Nucleocentric_DNA_SAMMed3D_Feature90,Nucleocentric_DNA_SAMMed3D_Feature91,Nucleocentric_DNA_SAMMed3D_Feature92,Nucleocentric_DNA_SAMMed3D_Feature93,Nucleocentric_DNA_SAMMed3D_Feature94,Nucleocentric_DNA_SAMMed3D_Feature95,Nucleocentric_DNA_SAMMed3D_Feature96,Nucleocentric_DNA_SAMMed3D_Feature97,Nucleocentric_DNA_SAMMed3D_Feature98,Nucleocentric_DNA_SAMMed3D_Feature99
0,257,E9-1,4.163089,-0.909741,0.539815,2.559543,0.119701,2.536916,2.289842,-2.520163,...,-0.007136,-0.050355,0.074250,-0.011046,0.016181,-0.065276,-0.113449,0.251154,0.341022,0.186649
1,514,E9-1,3.737707,-1.072771,3.544111,1.045316,-0.253289,2.919431,4.003189,-1.292669,...,-0.007064,-0.177103,0.064973,-0.010797,0.042807,-0.100086,0.030172,0.158761,0.354477,0.086128
2,771,E9-1,1.223940,0.595523,-0.261445,1.550906,-1.552259,4.213758,1.900936,-2.600322,...,-0.007628,-0.044639,0.042606,-0.010729,0.009675,-0.042756,-0.063998,0.216499,0.399424,0.182785
3,1285,E9-1,1.132286,-1.475073,1.012799,1.425551,-0.406091,0.720181,-0.450617,-1.883056,...,-0.007078,-0.066354,0.068478,-0.010734,0.010313,-0.063647,-0.056182,0.254585,0.337616,0.188783
4,1542,E9-1,3.574742,-0.808908,2.019418,0.285833,-2.775232,2.351737,2.334319,-0.803855,...,-0.007773,-0.051926,0.167763,-0.010880,0.012455,-0.125910,-0.045071,0.121093,0.403455,0.167635
5,1799,E9-1,1.442207,-2.732410,1.177282,0.571325,1.399111,1.592824,2.864717,0.262707,...,-0.007577,-0.058811,0.078695,-0.010628,0.016391,-0.027385,-0.046834,0.233832,0.339102,0.167775
6,2056,E9-1,2.643584,-2.437306,3.120502,-0.990144,-2.376880,1.122741,2.832258,0.278236,...,-0.007504,-0.087710,0.091699,-0.010816,0.045311,-0.095006,-0.080825,0.232428,0.345474,0.189369
7,2313,E9-1,-0.309827,1.975163,-1.053658,2.271537,0.098605,2.776303,1.638288,-0.553274,...,-0.005967,-0.074876,0.071930,-0.010702,0.022353,0.015701,0.001315,0.254712,0.306036,0.229803
8,2570,E9-1,1.010511,-0.205042,1.062148,0.461221,0.061294,5.251267,3.180134,-0.968768,...,-0.006304,-0.104988,0.094308,-0.011003,0.019935,-0.030390,-0.033140,0.239339,0.335525,0.179282
9,2827,E9-1,4.745710,-0.305881,1.841763,2.018081,0.791441,3.166679,3.432388,-2.207949,...,-0.008176,-0.082077,0.051097,-0.010106,0.037340,-0.060246,0.099444,0.117454,0.284037,0.088279
10,3084,E9-1,1.383267,1.378097,0.334026,-0.176060,0.987684,3.089379,3.221431,0.406874,...,-0.005296,-0.025166,0.052040,-0.010582,0.037506,-0.049521,0.030653,0.296081,0.325311,0.269562
11,3341,E9-1,2.240092,0.477945,-0.326472,1.616784,0.537799,2.542666,3.705081,-1.138036,...,-0.006233,-0.127333,-0.045692,-0.010670,0.029186,-0.071248,0.000466,0.215043,0.358277,0.112048
12,3598,E9-1,0.199609,-0.424837,-1.676538,1.436717,-1.642957,3.193325,4.104551,-4.907738,...,-0.006585,-0.051163,0.104844,-0.010769,0.037901,-0.025830,-0.014821,0.264788,0.321085,0.263131
13,3855,E9-1,1.176318,-1.034699,-0.728229,1.949154,-1.807414,3.227610,4.244695,-3.921506,...,-0.008756,-0.075361,0.052372,-0.010642,0.026605,-0.070970,-0.073953,0.216078,0.394049,0.216989
14,4112,E9-1,1.909687,-1.892440,0.458423,1.093116,0.422279,2.115582,2.833143,-0.055103,...,-0.007647,-0.068912,0.054775,-0.010765,0.019530,-0.062125,-0.043876,0.187555,0.335711,0.175512
15,4369,E9-1,2.385185,-3.007615,3.075416,-1.193577,-0.767873,2.733818,4.342608,1.642962,...,-0.007889,-0.105707,0.059493,-0.010392,0.016608,-0.029036,-0.046788,0.201045,0.316889,0.154940
16,4626,E9-1,2.952098,0.144043,0.540431,1.676805,-0.107997,2.946360,4.623004,-3.173507,...,-0.007800,-0.038575,0.053132,-0.010839,0.021072,-0.095893,-0.106412,0.216412,0.370898,0.210372
17,4883,E9-1,2.581453,-0.109001,1.498881,2.185197,-0.342353,3.021045,3.830744,-2.267307,...,-0.007822,-0.064501,0.055958,-0.010622,0.017342,-0.086149,-0.099795,0.209172,0.322813,0.171243
18,5397,E9-1,5.117232,1.273315,-0.147578,2.401250,0.212693,2.467849,3.034535,-3.131785,...,-0.006787,-0.058006,0.049920,-0.010679,0.016381,-0.069147,-0.076952,0.225841,0.351491,0.228556
19,5654,E9-1,4.767293,1.160215,-1.101451,2.471955,0.152581,3.891124,3.082396,-2.267425,...,-0.005279,-0.119595,-0.159197,-0.011066,0.003288,-0.091284,0.051071,0.120389,0.469314,0.087139
20,6168,E9-1,1.530138,1.885118,-2.739405,3.033035,-1.302173,5.159525,1.799415,-3.593683,...,-0.006388,-0.097608,0.018554,-0.011029,0.021758,-0.058110,-0.011752,0.222152,0.343824,0.147366
21,6425,E9-1,1.449379,-2.912999,0.493545,2.606451,1.560709,2.117713,0.670451,-1.008053,...,-0.005513,-0.081648,0.068031,-0.011043,0.021944,0.049029,0.070147,0.067511,0.286146,0.123928
22,6682,E9-1,2.166569,-1.245375,1.957455,0.007647,-0.267581,1.873949,5.079210,0.241310,...,-0.005636,-0.127902,-0.098877,-0.011259,0.008581,-0.030448,0.110627,0.145495,0.474090,0.062918
23,6939,E9-1,4.911654,-0.548494,2.938711,0.900765,-0.389040,2.453001,4.092182,-1.788029,...,-0.006023,-0.089091,-0.173329,-0.010975,-0.001860,-0.076318,0.117563,0.108140,0.527795,0.023779
24,7196,E9-1,3.584275,0.823499,-0.566261,0.942847,1.707169,3.794951,5.098351,-0.415559,...,-0.007606,-0.025856,0.038056,-0.010452,0.024839,-0.080409,-0.073593,0.193798,0.392283,0.222239
25,7453,E9-1,1.270390,-1.004952,1.698771,0.281582,-0.251286,2.125177,3.730649,-0.541941,...,-0.006381,-0.121920,-0.126305,-0.010630,0.022082,-0.054914,0.156417,0.206954,0.501453,0.130535
26,7710,E9-1,2.566468,2.362512,-0.263929,1.038718,-0.350511,3.994976,2.641053,-1.125375,...,-0.006852,-0.096626,-0.146780,-0.010461,0.036608,-0.053253,0.107442,0.223652,0.421822,0.138152
27,7967,E9-1,1.691077,-1.152639,1.028636,0.604235,0.814131,2.439511,6.218574,-0.532546,...,-0.008430,-0.061212,0.057374,-0.010674,0.033693,-0.087596,-0.074803,0.193344,0.401849,0.233793
28,8224,E9-1,2.056189,1.909328,-0.887135,-2.508188,0.527542,3.370633,1.529250,-1.108917,...,-0.006165,-0.113999,-0.017542,-0.010637,0.018252,-0.065166,0.009212,0.182379,0.311150,0.201926
29,8481,E9-1,3.334000,-1.444953,0.786996,1.905913,0.264375,3.155921,-0.135211,-1.566094,...,-0.006459,-0.102069,-0.079186,-0.010890,0.006653,-0.103867,0.130098,0.111750,0.504574,0.009937
30,8738,E9-1,5.231504,-0.693916,2.161409,1.503377,0.158391,3.077693,4.656122,-2.961315,...,-0.008320,-0.014142,-0.010844,-0.010824,0.025649,-0.065072,-0.086127,0.167222,0.413316,0.168226
31,8995,E9-1,3.309433,0.599456,-0.449371,-2.043761,1.478683,3.218665,3.453495,-1.629472,...,-0.008552,-0.076884,0.077517,-0.010403,0.022621,-0.093074,-0.084568,0.163657,0.283065,0.201077

In [43]:
# merge the dfs such that each compartment has a single df with all feature types as columns
compartment_dfs = {}
for compartment in final_df_dict.keys():
    for df in final_df_dict[compartment].values():
        # if compartment == "Nucleocentric":
        #     compartment_dfs[compartment] = df
        #     break

        compartment_dfs[compartment] = reduce(
            lambda left, right: pd.merge(
                left,
                right,
                on=["object_id", "image_set"],
                how="left",
            ),
            final_df_dict[compartment].values(),
        )

In [44]:
# assert that the number of Nuclei, Cell, Cytoplasm, Nucleocentric are all the same
print(
    len(compartment_dfs["Nuclei"]),
    len(compartment_dfs["Cell"]),
    len(compartment_dfs["Cytoplasm"]),
    len(compartment_dfs["Nucleocentric"]),
)
assert (
    len(compartment_dfs["Nuclei"])
    == len(compartment_dfs["Cell"])
    == len(compartment_dfs["Cytoplasm"])
    == len(compartment_dfs["Nucleocentric"])
)

# assert that all object ids line up across compartments
assert (
    compartment_dfs["Nuclei"]["object_id"].equals(compartment_dfs["Cell"]["object_id"])
    and compartment_dfs["Nuclei"]["object_id"].equals(
        compartment_dfs["Cytoplasm"]["object_id"]
    )
    and compartment_dfs["Nuclei"]["object_id"].equals(
        compartment_dfs["Nucleocentric"]["object_id"]
    )
)

32 32 32 32

In [45]:
compartment_dfs["Nucleocentric"]

,object_id,image_set,Nucleocentric_Mito_CHAMMI75_Feature0_x,Nucleocentric_Mito_CHAMMI75_Feature1_x,Nucleocentric_Mito_CHAMMI75_Feature10_x,Nucleocentric_Mito_CHAMMI75_Feature100_x,Nucleocentric_Mito_CHAMMI75_Feature101_x,Nucleocentric_Mito_CHAMMI75_Feature102_x,Nucleocentric_Mito_CHAMMI75_Feature103_x,Nucleocentric_Mito_CHAMMI75_Feature104_x,...,Nucleocentric_ER_CHAMMI75_Feature90_y,Nucleocentric_ER_CHAMMI75_Feature91_y,Nucleocentric_ER_CHAMMI75_Feature92_y,Nucleocentric_ER_CHAMMI75_Feature93_y,Nucleocentric_ER_CHAMMI75_Feature94_y,Nucleocentric_ER_CHAMMI75_Feature95_y,Nucleocentric_ER_CHAMMI75_Feature96_y,Nucleocentric_ER_CHAMMI75_Feature97_y,Nucleocentric_ER_CHAMMI75_Feature98_y,Nucleocentric_ER_CHAMMI75_Feature99_y
0,257,E9-1,4.163089,-0.909741,0.539815,2.559543,0.119701,2.536916,2.289842,-2.520163,...,0.772643,5.292253,-11.560932,2.214991,5.065310,-2.337864,0.853876,3.678142,1.301484,-1.591434
1,514,E9-1,3.737707,-1.072771,3.544111,1.045316,-0.253289,2.919431,4.003189,-1.292669,...,1.230746,6.550419,-10.415889,4.427794,2.895350,-0.918173,-2.929753,3.686656,1.196309,-1.429748
2,771,E9-1,1.223940,0.595523,-0.261445,1.550906,-1.552259,4.213758,1.900936,-2.600322,...,-1.953734,6.983423,-6.470373,6.091298,-0.854538,1.003946,-1.052528,4.367959,-3.134054,-2.874774
3,1285,E9-1,1.132286,-1.475073,1.012799,1.425551,-0.406091,0.720181,-0.450617,-1.883056,...,0.741673,3.478837,-5.227507,6.752029,0.123695,3.283154,-2.657704,2.571409,-3.321669,-2.781133
4,1542,E9-1,3.574742,-0.808908,2.019418,0.285833,-2.775232,2.351737,2.334319,-0.803855,...,1.707944,4.549797,-3.489297,6.379190,-3.014529,4.498521,-4.837077,4.436558,1.575774,-0.253532
5,1799,E9-1,1.442207,-2.732410,1.177282,0.571325,1.399111,1.592824,2.864717,0.262707,...,-0.403066,4.035362,-5.553319,8.353971,-0.053020,0.462281,-0.853180,5.318773,-4.143157,-1.343526
6,2056,E9-1,2.643584,-2.437306,3.120502,-0.990144,-2.376880,1.122741,2.832258,0.278236,...,0.108406,5.560587,-6.107862,7.789940,3.009899,3.438133,-0.975063,3.404965,-3.471829,-0.503241
7,2313,E9-1,-0.309827,1.975163,-1.053658,2.271537,0.098605,2.776303,1.638288,-0.553274,...,-1.832377,5.927807,-12.283434,-0.646739,2.273872,-2.244855,1.008664,5.524864,-0.751357,-2.016670
8,2570,E9-1,1.010511,-0.205042,1.062148,0.461221,0.061294,5.251267,3.180134,-0.968768,...,0.704557,4.299072,-10.926056,-0.220481,3.679306,-3.864789,0.787039,2.879037,-2.291432,-1.569307
9,2827,E9-1,4.745710,-0.305881,1.841763,2.018081,0.791441,3.166679,3.432388,-2.207949,...,-0.030813,2.789876,-9.114958,4.489854,1.673064,0.954411,-3.508823,4.099704,1.295795,-2.921562
10,3084,E9-1,1.383267,1.378097,0.334026,-0.176060,0.987684,3.089379,3.221431,0.406874,...,-1.355198,4.769260,-9.764332,1.772401,4.557551,-1.279822,0.163700,5.470457,2.349365,-0.348863
11,3341,E9-1,2.240092,0.477945,-0.326472,1.616784,0.537799,2.542666,3.705081,-1.138036,...,-0.980980,7.274001,-7.350552,4.080503,4.268709,0.242637,0.063136,6.945713,2.845742,0.065145
12,3598,E9-1,0.199609,-0.424837,-1.676538,1.436717,-1.642957,3.193325,4.104551,-4.907738,...,0.407463,-1.477368,-7.204495,-1.094320,0.149788,-1.932430,-4.491848,6.063048,3.220149,-1.797358
13,3855,E9-1,1.176318,-1.034699,-0.728229,1.949154,-1.807414,3.227610,4.244695,-3.921506,...,1.203352,-2.322122,-7.385558,-2.130180,0.559831,-4.340273,-3.596020,2.894045,0.978324,-0.387763
14,4112,E9-1,1.909687,-1.892440,0.458423,1.093116,0.422279,2.115582,2.833143,-0.055103,...,-2.273616,2.425344,-5.460361,8.446286,-1.151055,2.244632,0.042883,2.218584,-2.932600,-5.578367
15,4369,E9-1,2.385185,-3.007615,3.075416,-1.193577,-0.767873,2.733818,4.342608,1.642962,...,-0.287281,3.581105,-4.738784,8.444276,-1.044622,3.907043,-0.564236,1.872277,-3.145437,-4.253002
16,4626,E9-1,2.952098,0.144043,0.540431,1.676805,-0.107997,2.946360,4.623004,-3.173507,...,-2.786491,8.361675,-7.331019,3.933644,3.844556,-2.093340,0.507700,6.504025,1.603282,-0.056144
17,4883,E9-1,2.581453,-0.109001,1.498881,2.185197,-0.342353,3.021045,3.830744,-2.267307,...,3.605274,1.495474,-7.543643,4.738726,-1.737611,1.931633,-4.879454,4.559751,1.541545,-2.884855
18,5397,E9-1,5.117232,1.273315,-0.147578,2.401250,0.212693,2.467849,3.034535,-3.131785,...,0.759814,2.289906,-6.731227,5.434904,-1.102515,3.314713,-2.772719,2.251014,-1.396754,-6.417315
19,5654,E9-1,4.767293,1.160215,-1.101451,2.471955,0.152581,3.891124,3.082396,-2.267425,...,1.697185,2.430094,-7.206137,6.073257,-1.014416,0.484766,-1.685726,3.751933,1.553914,-5.430534
20,6168,E9-1,1.530138,1.885118,-2.739405,3.033035,-1.302173,5.159525,1.799415,-3.593683,...,1.533741,4.462725,-0.376840,7.289914,-3.564250,4.410809,-0.265076,1.060253,-4.325473,-0.793288
21,6425,E9-1,1.449379,-2.912999,0.493545,2.606451,1.560709,2.117713,0.670451,-1.008053,...,-0.705787,7.730712,-7.350419,6.301606,2.084299,2.411495,-0.185873,4.145314,0.580659,1.519776
22,6682,E9-1,2.166569,-1.245375,1.957455,0.007647,-0.267581,1.873949,5.079210,0.241310,...,-2.102747,7.337782,-7.308294,4.232917,2.091058,1.398864,0.163640,7.740788,2.587727,1.853531
23,6939,E9-1,4.911654,-0.548494,2.938711,0.900765,-0.389040,2.453001,4.092182,-1.788029,...,1.192227,4.370824,-9.027699,4.864946,2.736150,-0.068407,-2.594394,3.136391,4.595163,-2.580759
24,7196,E9-1,3.584275,0.823499,-0.566261,0.942847,1.707169,3.794951,5.098351,-0.415559,...,-0.222123,7.127327,-12.004992,0.385647,2.980462,0.125779,-3.328448,7.424027,2.074309,-3.605236
25,7453,E9-1,1.270390,-1.004952,1.698771,0.281582,-0.251286,2.125177,3.730649,-0.541941,...,-2.282848,8.195208,-8.402483,5.085462,3.280633,2.581679,-0.292243,6.775833,3.782032,-1.135504
26,7710,E9-1,2.566468,2.362512,-0.263929,1.038718,-0.350511,3.994976,2.641053,-1.125375,...,0.789464,6.132333,-10.835147,-2.680300,-1.295260,-3.143446,-1.991241,4.279894,0.327833,-1.353994
27,7967,E9-1,1.691077,-1.152639,1.028636,0.604235,0.814131,2.439511,6.218574,-0.532546,...,2.507580,3.618482,-11.318316,-1.874329,3.145672,-6.178816,-1.960529,1.233065,0.149835,-2.341513
28,8224,E9-1,2.056189,1.909328,-0.887135,-2.508188,0.527542,3.370633,1.529250,-1.108917,...,-2.633522,4.548102,-6.091544,6.881670,-0.359147,0.989809,-1.534197,3.496697,-4.346956,-5.494694
29,8481,E9-1,3.334000,-1.444953,0.786996,1.905913,0.264375,3.155921,-0.135211,-1.566094,...,0.106377,7.246470,-8.431348,6.385227,1.551273,2.900985,-2.974907,4.932635,-0.336790,2.210328
30,8738,E9-1,5.231504,-0.693916,2.161409,1.503377,0.158391,3.077693,4.656122,-2.961315,...,-0.583200,6.264256,-6.445580,7.944726,-2.304801,2.554319,-1.714273,2.866293,-2.440795,-4.253689
31,8995,E9-1,3.309433,0.599456,-0.449371,-2.043761,1.478683,3.218665,3.453495,-1.629472,...,-4.230435,8.810007,-8.260854,3.325674,1.565059,-0.237013,-2.197417,6.590217,1.117981,-5.668416

In [39]:
nuclei_ids = compartment_dfs["Nuclei"]["object_id"].unique()
nuclei_ids = [x * 257 for x in nuclei_ids]
cell_ids = compartment_dfs["Cell"]["object_id"].unique()

print(nuclei_ids)
print(cell_ids)
set(nuclei_ids) - set(cell_ids)

[np.int64(66049), np.int64(132098), np.int64(198147), np.int64(330245), np.int64(396294), np.int64(462343), np.int64(528392), np.int64(594441), np.int64(660490), np.int64(726539), np.int64(792588), np.int64(858637), np.int64(924686), np.int64(990735), np.int64(1056784), np.int64(1122833), np.int64(1188882), np.int64(1254931), np.int64(1387029), np.int64(1453078), np.int64(1585176), np.int64(1651225), np.int64(1717274), np.int64(1783323), np.int64(1849372), np.int64(1915421), np.int64(1981470), np.int64(2047519), np.int64(2113568), np.int64(2179617), np.int64(2245666), np.int64(2311715)]
[ 257  514  771 1285 1542 1799 2056 2313 2570 2827 3084 3341 3598 3855
 4112 4369 4626 4883 5397 5654 6168 6425 6682 6939 7196 7453 7710 7967
 8224 8481 8738 8995]

{np.int64(66049),
 np.int64(132098),
 np.int64(198147),
 np.int64(330245),
 np.int64(396294),
 np.int64(462343),
 np.int64(528392),
 np.int64(594441),
 np.int64(660490),
 np.int64(726539),
 np.int64(792588),
 np.int64(858637),
 np.int64(924686),
 np.int64(990735),
 np.int64(1056784),
 np.int64(1122833),
 np.int64(1188882),
 np.int64(1254931),
 np.int64(1387029),
 np.int64(1453078),
 np.int64(1585176),
 np.int64(1651225),
 np.int64(1717274),
 np.int64(1783323),
 np.int64(1849372),
 np.int64(1915421),
 np.int64(1981470),
 np.int64(2047519),
 np.int64(2113568),
 np.int64(2179617),
 np.int64(2245666),
 np.int64(2311715)}

In [40]:
with duckdb.connect(DB_structure_path, read_only=True) as cx:
    organoid_table = cx.execute("SELECT * FROM Organoid").df()
    cell_table = cx.execute("SELECT * FROM Cell").df()
    nuclei_table = cx.execute("SELECT * FROM Nuclei").df()
    cytoplasm_table = cx.execute("SELECT * FROM Cytoplasm").df()
    nucleocentric_table = cx.execute("SELECT * FROM Nucleocentric").df()

dict_of_DB_structues = {
    "Organoid": organoid_table,
    "Cell": cell_table,
    "Nuclei": nuclei_table,
    "Cytoplasm": cytoplasm_table,
    "Nucleocentric": nucleocentric_table,
}

In [41]:
# get the table from the DB_structue
with duckdb.connect(sqlite_path, read_only=False) as cx:
    for compartment, df in compartment_dfs.items():
        print(compartment, df.shape)
        if df.empty:
            cx.register("temp_df", dict_of_DB_structues[compartment])
            cx.execute(
                f"CREATE OR REPLACE TABLE {compartment} AS SELECT * FROM temp_df"
            )
            cx.unregister("temp_df")
        else:
            cx.register("temp_df", df)
            cx.execute(
                f"CREATE OR REPLACE TABLE {compartment} AS SELECT * FROM temp_df"
            )
            cx.unregister("temp_df")

Organoid (1, 3961)
Nuclei (32, 3963)
Cell (32, 3961)
Cytoplasm (32, 3961)
Nucleocentric (32, 4610)